### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anbraten** [lagossapp/lagoss#1]
- [  ] finish <lagoss.com> setup
  - [ ] deploy dashboard to <app.lagoss.com>
  - [ ] check how to update vercel env without need to re-deploy
  - [ ] deploy runtime
  - [ ] deploy s3
  - [ ] deploy clickhouse
- [ ] remove some unused parts
  - [ ] sentry
  - [ ] axiom
  - [ ] posthog
- [ ]
