### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by anbraten** [lagossapp/lagoss#10]
- [ ] connect project to git repo
- [ ] build new deployments on push
- [ ] main => prod deployment
- [ ] PR => preview deployment (require approval for 3rd party PRs)
- [ ] link commit / PR in UI
